"""Config + secrets loading.

Secrets come from environment variables (systemd EnvironmentFile=).
Everything else comes from a JSON file pointed to by ANDUIN_CONFIG, generated by
the NixOS module from its declarative options.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Secrets(BaseSettings):
    model_config = SettingsConfigDict(env_file=None, case_sensitive=False, extra="ignore")

    # Each may be empty in isolation if only one extractor is invoked.
    google_health_client_id: str = ""
    google_health_client_secret: str = ""

    withings_client_id: str = ""
    withings_client_secret: str = ""

    intervals_api_key: str = ""
    intervals_athlete_id: str = ""

    liftosaur_api_key: str = ""

    database_url: str = Field(min_length=1)


class GoogleHealthConfig(BaseModel):
    enabled: bool = True
    today_window_hours: int = 24
    backfill_window_days: int = 7


class WithingsConfig(BaseModel):
    enabled: bool = True
    window_days: int = 14


class IntervalsConfig(BaseModel):
    enabled: bool = True
    window_days: int = 3
    pull_streams: bool = True


class LiftosaurConfig(BaseModel):
    enabled: bool = True
    window_days: int = 7


class FileConfig(BaseModel):
    state_dir: Path = Path("/var/lib/anduin/state")
    google_health: GoogleHealthConfig = GoogleHealthConfig()
    withings: WithingsConfig = WithingsConfig()
    intervals: IntervalsConfig = IntervalsConfig()
    liftosaur: LiftosaurConfig = LiftosaurConfig()


@dataclass
class AppConfig:
    secrets: Secrets
    file: FileConfig


def load() -> AppConfig:
    cfg_path_env = os.environ.get("ANDUIN_CONFIG")
    if cfg_path_env:
        cfg_path = Path(cfg_path_env)
        if not cfg_path.exists():
            raise RuntimeError(f"Config file does not exist: {cfg_path}")
        file_data = json.loads(cfg_path.read_text())
        file_cfg = FileConfig.model_validate(file_data)
    else:
        file_cfg = FileConfig()
    state_override = os.environ.get("STATE_DIRECTORY")
    if state_override:
        file_cfg.state_dir = Path(state_override.split(":")[0])
    return AppConfig(secrets=Secrets(), file=file_cfg)
