"""Config + secrets loading.

Secrets come from environment variables (systemd EnvironmentFile=).
Everything else comes from a JSON file pointed to by ANDUIN_CONFIG, generated by
the NixOS module from its declarative options.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Secrets(BaseSettings):
    # Real environment variables (systemd EnvironmentFile= in production) take
    # precedence; a `.env` in the working directory is read as a convenience for
    # local development. A missing .env is ignored.
    model_config = SettingsConfigDict(env_file=".env", case_sensitive=False, extra="ignore")

    # Each may be empty in isolation if only one extractor is invoked.
    google_health_client_id: str = ""
    google_health_client_secret: str = ""

    withings_client_id: str = ""
    withings_client_secret: str = ""

    intervals_api_key: str = ""
    intervals_athlete_id: str = ""

    liftosaur_api_key: str = ""

    database_url: str = Field(min_length=1)

    # Dev override for the state dir (where OAuth tokens are persisted). Lets you
    # avoid the hardcoded /var/lib/anduin/state default without root. Set via env
    # or .env as ANDUIN_STATE_DIR; takes precedence over systemd's STATE_DIRECTORY.
    anduin_state_dir: str = ""


class GoogleHealthConfig(BaseModel):
    enabled: bool = True
    today_window_hours: int = 24
    backfill_window_days: int = 7


class WithingsConfig(BaseModel):
    enabled: bool = True
    window_days: int = 14


class IntervalsConfig(BaseModel):
    enabled: bool = True
    window_days: int = 3
    pull_streams: bool = True


class LiftosaurConfig(BaseModel):
    enabled: bool = True
    window_days: int = 7


class FileConfig(BaseModel):
    state_dir: Path = Path("/var/lib/anduin/state")
    # Owner of every ingested row. anduin is single-user today; the extractors
    # stamp this id on all raw rows (it's folded into each table's natural key),
    # so multi-user support later is a read-path change only. Defaults to the
    # single seeded user (identity.users id = 1).
    user_id: int = 1
    google_health: GoogleHealthConfig = GoogleHealthConfig()
    withings: WithingsConfig = WithingsConfig()
    intervals: IntervalsConfig = IntervalsConfig()
    liftosaur: LiftosaurConfig = LiftosaurConfig()


@dataclass
class AppConfig:
    secrets: Secrets
    file: FileConfig


def load() -> AppConfig:
    cfg_path_env = os.environ.get("ANDUIN_CONFIG")
    if cfg_path_env:
        cfg_path = Path(cfg_path_env)
        if not cfg_path.exists():
            raise RuntimeError(f"Config file does not exist: {cfg_path}")
        file_data = json.loads(cfg_path.read_text())
        file_cfg = FileConfig.model_validate(file_data)
    else:
        file_cfg = FileConfig()
    secrets = Secrets()
    # State-dir override precedence: explicit ANDUIN_STATE_DIR (dev, also via
    # .env) beats systemd's STATE_DIRECTORY, which beats the config default.
    state_override = secrets.anduin_state_dir or os.environ.get("STATE_DIRECTORY", "")
    if state_override:
        file_cfg.state_dir = Path(state_override.split(":")[0])
    return AppConfig(secrets=secrets, file=file_cfg)
