CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS canonical;

-- Owner identity. anduin is single-user today, but every measurement row carries
-- a user_id (folded into its natural key) so multi-user support can be added
-- later as a read-path change only -- no data migration, no re-keying of the
-- hypertables or continuous aggregates. Created here, before the first FK
-- reference in 0003, and seeded with a single row (id = 1). Future inserts
-- autoincrement from there; the write path always stamps the configured owner id.
CREATE SCHEMA IF NOT EXISTS identity;

CREATE TABLE IF NOT EXISTS identity.users (
    id           int         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     text        NOT NULL UNIQUE,
    display_name text,
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- Let the identity sequence assign id = 1 to the first row (rather than forcing
-- it), so the sequence advances to 2 and a future second user won't collide on
-- id = 1. The write path's default owner id (config user_id = 1) matches this.
INSERT INTO identity.users (username, display_name)
    VALUES ('aiden', 'Aiden')
    ON CONFLICT (username) DO NOTHING;
